-- Mind Master realtime multiplayer schema
-- Run this in Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.mm_rooms (
  id uuid primary key default gen_random_uuid(),
  room_code text unique not null,
  game_type text not null default 'math-rush',
  status text not null default 'WAITING' check (status in ('WAITING','READY','COUNTDOWN','PLAYING','FINISHED','REMATCH','CLOSED')),
  player1_id text,
  player2_id text,
  player1_name text,
  player2_name text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '2 hours')
);

create table if not exists public.mm_events (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.mm_rooms(id) on delete cascade,
  player_id text not null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists mm_rooms_code_idx on public.mm_rooms(room_code);
create index if not exists mm_events_room_idx on public.mm_events(room_id, id);

alter table public.mm_rooms enable row level security;
alter table public.mm_events enable row level security;

-- This prototype uses anonymous/public room access. Scores are never treated as trusted.
-- Tighten these policies before using the game for a public competitive service.
drop policy if exists "rooms read" on public.mm_rooms;
drop policy if exists "rooms insert" on public.mm_rooms;
drop policy if exists "rooms update" on public.mm_rooms;
drop policy if exists "events read" on public.mm_events;
drop policy if exists "events insert" on public.mm_events;
create policy "rooms read" on public.mm_rooms for select using (expires_at > now());
create policy "rooms insert" on public.mm_rooms for insert with check (expires_at > now());
create policy "rooms update" on public.mm_rooms for update using (expires_at > now()) with check (expires_at > now());
create policy "events read" on public.mm_events for select using (exists (select 1 from public.mm_rooms r where r.id=room_id and r.expires_at > now()));
create policy "events insert" on public.mm_events for insert with check (exists (select 1 from public.mm_rooms r where r.id=room_id and r.expires_at > now()));

-- Enable realtime for both tables.
alter publication supabase_realtime add table public.mm_rooms;
alter publication supabase_realtime add table public.mm_events;
